# Generated by Django 5.1.4 on 2025-10-25 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Kastriot Tanaj', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, help_text='Category or topic of the post', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='', help_text='Write your article here'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from the title', unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Enter the title of the blog post', max_length=200),
        ),
    ]
